from Tkinter import *
import Tkinter as tk
from Tkinter import messagebox as mbox
fen=Tk()
fen.title('Auto-école Sousse')
txt1=Label(fen, text='Auto-école Sousse', fg='purple')
txt1.grid(row=0)
txt2=Label(fen, text='Bienvenue cher client,tentez de séléctionner vos choix', fg='blue')
txt2.grid(row=1)
txt3=Label(fen, text='saisir votre nom et prénom : ')
txt3.grid(row=2)
txt4=Label(fen, text='saisir votre C.I.N : ')
txt4.grid(row=3)
txt5=Label(fen, text='saisir votre G.S.M : ')
txt5.grid(row=4)
txt6=Label(fen, text="Saisir votre voiture désirée :")
txt6.grid(row=7)
e1=Entry(fen)
e1.grid(row=2, column=1)
e2=Entry(fen)
e2.grid(row=3, column=1)
e3=Entry(fen)
e3.grid(row=4, column=1)
txt7=Label(fen, text='Saisir votre circuit désirée: ')
txt7.grid(row=9)
txt8=Label(fen,text="nombre d'heures de conduite")
txt8.grid(row=5)
txt9=Label(fen,text="prix d'heures : 15dt")
txt9.grid(row=6)
e4=Entry(fen)
e4.grid(row=5,column=1)
varchoix=tk.StringVar()
v1=Radiobutton(fen, text='POLO', variable=varchoix, value='POLO')
v1.grid(row=8, column=0)
v2=Radiobutton(fen, text='CLIO', variable=varchoix, value='CLIO')
v2.grid(row=8, column=1)
v3=Radiobutton(fen, text='PEUGEOT', variable=varchoix, value='PEUGEOT')
v3.grid(row=8, column=2)
choix1=tk.StringVar()
choix2=tk.StringVar()
c1=Checkbutton(fen, text='HMS', variable=choix1, onvalue='HMS', offvalue='')
c1.grid(row=10, column=0)
c2=Checkbutton(fen, text='KANTAOUI', variable=choix2, onvalue='KANTAOUI', offvalue='')
c2.grid(row=10, column=1)
b2=Button(fen, text='quitter', command=fen.destroy, bg='red', fg='white')
b2.grid(row=11, column=1)
def login():
    h1=e1.get()
    h2=e2.get()
    h3=float(e3.get())
    h4=float(e4.get())
    h5=varchoix.get()
    h6=choix1.get()
    h8=choix2.get()
    h7=h4*5
    fen1=Tk()
    fen1.title('Votre fiche')
    l1=Label(fen1,text='Nom et prénnom :'  +h1 ,fg='blue')
    l1.pack()
    l2=Label(fen1,text= 'C.I.N :'  +h2 ,fg='green')
    l2.pack()
    l3=Label(fen1,text= 'G.S.M :'  +str(h3) ,fg='red')
    l3.pack()
    l4=Label(fen1,text='Montant :' +str(h7)+"dt" ,fg='orange')
    l4.pack()
    l5=Label(fen1,text="Voiture désirée  : "  ""+h5 ,fg='yellow')
    l5.pack()
    l6=Label(fen1,text='Circuit désiré : '+' '+h6+''+h8 ,fg='pink')
    l6.pack()
    b3=Button(fen1,text='confirmer',command=fen1.destroy,bg='green',fg='white')
    b3.pack()
b1=Button(fen, text='terminer', command=login, bg='green', fg='white')
b1.grid(row=11, column=0)
fen.mainloop()
