from tkinter import *
import tkinter as tk
from tkinter import messagebox as mbox
fen=Tk()
fen.title('PIZZA HUT')
txt1=Label(fen, text=' PIZZA HUT VOUS DIT BIENVENUE', fg='pink')
txt1.grid(row=0)
txt2=Label(fen, text=' CHER CLIENT , TENTEZ DE REMPLIR VOTRE FICHE DE COMMANDE :', fg='blue')
txt2.grid(row=1)
txt3=Label(fen, text='SAISIR VOTRE NOM ET PRENOM: ')
txt3.grid(row=2)
txt4=Label(fen, text='SAISIR LE N° DE VOTRE TABLE: ')
txt4.grid(row=3)
txt5=Label(fen, text="SAISIR VOTRE MOYEN DE PAIEMENT :")
txt5.grid(row=7)
e1=Entry(fen)
e1.grid(row=2, column=1)
e2=Entry(fen)
e2.grid(row=3, column=1)
txt6=Label(fen, text='SAISIR VOTRE COMMANDE')
txt6.grid(row=9)
txt7=Label(fen,text="SAISIR VOTRE QUANTITE DESIREE ")
txt7.grid(row=5)
txt8=Label(fen,text="PRIX D'UN MORCEAU : 5dt")
txt8.grid(row=6)
e3=Entry(fen)
e3.grid(row=5,column=1)
varchoix=tk.StringVar()
v1=Radiobutton(fen, text='Chèque', variable=varchoix, value='Chèque')
v1.grid(row=8, column=0)
v2=Radiobutton(fen, text='Carte bancaire', variable=varchoix, value='Carte bancaire')
v2.grid(row=8, column=1)
v3=Radiobutton(fen, text='Espèces', variable=varchoix, value='Espèces')
v3.grid(row=8, column=2)
choix1=tk.StringVar()
choix2=tk.StringVar()
choix3=tk.StringVar()
c1=Checkbutton(fen, text='Italian Pizza ', variable=choix1, onvalue='Italian Pizza', offvalue='')
c1.grid(row=10, column=0)
c2=Checkbutton(fen, text='Spanish Pizza ', variable=choix2, onvalue='Spanish Pizza', offvalue='')
c2.grid(row=10, column=1)
c3=Checkbutton(fen, text='Chicago Pizza ', variable=choix3, onvalue='Chicago Pizza', offvalue='')
c3.grid(row=10, column=2)
b2=Button(fen, text='QUITTER', command=fen.destroy, bg='red', fg='white')
b2.grid(row=11, column=1)
def valider():
    p1=e1.get()
    p2=e2.get()
    p3=float(e3.get())
    p4=varchoix.get()
    p5=choix1.get()
    p6=choix2.get()
    p7=choix3.get()
    p8=p3*5
    fen1=Tk()
    fen1.title('VOTRE FICHE DE COMMANDE ')
    l1=Label(fen1,text='NOM ET PRENOM :'  +p1 )
    l1.pack()
    l2=Label(fen1,text= ' N° DU TABLE :'  +p2 )
    l2.pack()
    l3=Label(fen1,text='MONTANT :' +str(p8)+"dt" )
    l3.pack()
    l4=Label(fen1,text="MOYEN DE PAIEMENT  : "  ""+p4 )
    l4.pack()
    l5=Label(fen1,text='LA COMMANDE : '+'   '+p5+'   '+p6+'   '+p7)
    l5.pack()
    l6=Label(fen1,text='BON APPETIT!')
    b3=Button(fen1,text='CONFIRMER',command=fen1.destroy,bg='green',fg='white')
    b3.pack()
b1=Button(fen, text='TERMINER', command=valider, bg='green', fg='white')
b1.grid(row=11, column=0)

fen.mainloop()


